# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20241119-141416-acute-keyword

# Configuration for Rasa NLU.
language: it

# The pipeline for NLU. It includes components for tokenization, featurization, and classification.
pipeline:
  - name: WhitespaceTokenizer  # Tokenizer che suddivide il testo in parole
  - name: RegexEntityExtractor  # Estrae entità definite tramite espressioni regolari
  - name: CRFEntityExtractor   # Un altro estrattore che può riconoscere entità più complesse
  - name: CountVectorsFeaturizer  # Featurizer per estrarre caratteristiche dal testo
  - name: DIETClassifier  # Un modello neurale per l'estrazione delle entità
    epochs: 100  # Aumenta il numero di epoche per il training
  - name: EntitySynonymMapper  # Mappa le entità ai sinonimi definiti nel dominio
  - name: ResponseSelector  # Per rispondere in base alla selezione della risposta
    epochs: 100
  - name: FallbackClassifier  # Gestisce risposte di fallback quando il modello è incerto
    threshold: 0.3  # Soglia di confidenza per il fallback
    ambiguity_threshold: 0.1  # Ambiguità nelle risposte

# Configuration for Rasa Core.
# This section configures policies that govern how your bot responds to user inputs.
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
