version: "3.1"

intents:
  - greet
  - goodbye
  - inform_courses
  - ask_help
  - bot_challenge         
  - provide_course_type
  - ask_lessons
  - ask_lessons_by_year 

entities:
  - course_type
  - start_date
  - end_date
  - year     #anno accademico frequentato

slots:
  start_date:
    type: text
    influence_conversation: true
    mappings:
      - type: from_entity
        entity: start_date  # Mappa l'entità start_date allo slot start_date

  end_date:
    type: text
    influence_conversation: true
    mappings:
      - type: from_entity
        entity: end_date  # Mappa l'entità end_date allo slot end_date

  course_type:
    type: text
    influence_conversation: true
    mappings:
      - type: from_entity
        entity: course_type  # Mappa l'entità course_type allo slot course_type

responses:
  utter_greet:
    - text: "Ciao! Come posso aiutarti oggi?"
  utter_goodbye:
    - text: "Arrivederci! Spero di rivederti presto."
  utter_courses_info:
    - text: "I corsi disponibili includono {course_type}."
  utter_default:
    - text: "Mi scuso, non ho capito. Puoi riformulare?"
  utter_iamabot:
    - text: "Sono un bot creato per aiutarti!" 
  utter_ask_help:  
    - text: "In cosa posso aiutarti?"
  #utter_ask_for_dates:
  #  - text: "Per favore, forniscimi le date di inizio e fine nel formato 'gg mese'."

  utter_year_lessons:
    - text: "Ecco le lezioni per l'anno {anno}."
  

actions:
  - action_get_lessons
  - action_provide_course_info
  - action_get_lessons_by_year

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
    case_sensitive: False
    regex:
      - name: year
        pattern: "(1|primo|2|secondo|3|terzo)" #associa le parole ai numeri
